apiVersion: kopf.dev/v1
kind: MLFlow
metadata:
  name: lstm-pipeline
  namespace: ml-faas
spec:
  pipeline:
    stage1:
      name: data-preprocess
      namespace: openfaas-fn
      schedulerName: default-scheduler
      rule: ['dev', 'user']
      step:
      - name: load-data
        mlfun: james759426/lstm-load-data:0.0.1
      - name: time-parser
        mlfun: james759426/lstm-time-parser:0.0.1
      - name: data-clean
        mlfun: james759426/lstm-data-clean:0.0.1
    stage2:
      name: LSTM-model-build
      namespace: openfaas-fn
      schedulerName: default-scheduler
      rule: ['dev']
      step:
      - name: train-data-build
        mlfun: james759426/lstm-train-data-build:0.0.1
      - name: train-model-build
        mlfun: james759426/lstm-train-model-build:0.0.1
      - name: train-model
        mlfun: james759426/lstm-train-model:0.0.1
    stage3:
      name: model-serving
      namespace: openfaas-fn
      schedulerName: default-scheduler
      rule: ['dev', 'user']
      step:
      - name: model-serving-fun
        mlfun: james759426/lstm-model-serving-fun:0.0.1